const List<Map<String, dynamic>> ESTADOS = [
  {"estado": "Acre", "casos": 72, "morte": 2, "letalidade": 2.8},
  {"estado": "Alagoas", "casos": 48, "morte": 3, "letalidade": 6.3},
  {"estado": "Amapá", "casos": 193, "mort,e": 3, "letalidade": 1.6},
  {"estado": "Amazonas", "casos": 1050, "morte": 53, "letalidade": 5.0},
  {"estado": "Bahia", "casos": 635, "morte": 21, "letalidade": 3.3},
  {"estado": "Ceará", "casos": 1582, "morte": 67, "letalidade": 4.2},
  {"estado": "Distrito Federal", "casos": 579, "morte": 14, "letalidade": 2.4},
  {"estado": "Espírito Santo", "casos": 349, "morte": 9, "letalidade": 2.6},
  {"estado": "Goiás", "casos": 209, "morte": 10, "letalidade": 4.8},
  {"estado": "Maranhão", "casos": 344, "morte": 21, "letalidade": 6.1},
  {"estado": "Mato Grosso", "casos": 121, "morte": 3, "letalidade": 2.5},
  {"estado": "Mato Grosso do Sul", "casos": 100, "morte": 2, "letalidade": 2.0},
  {"estado": "Minas Gerais", "casos": 750, "morte": 17, "letalidade": 2.3},
  {"estado": "Paraná", "casos": 676, "morte": 26, "letalidade": 3.8},
  {"estado": "Paraíba", "casos": 85, "morte": 11, "letalidade": 12.9},
  {"estado": "Pará", "casos": 217, "morte": 10, "letalidade": 4.6},
  {"estado": "Pernambuco", "casos": 816, "morte": 72, "letalidade": 8.8},
  {"estado": "Piauí", "casos": 41, "morte": 7, "letalidade": 17.1},
  {
    "estado": "Rio Grande do Norte",
    "casos": 289,
    "morte": 13,
    "letalidade": 4.5
  },
  {"estado": "Rio Grande do Sul", "casos": 640, "morte": 15, "letalidade": 2.3},
  {"estado": "Rio de Janeiro", "casos": 2607, "morte": 155, "letalidade": 5.9},
  {"estado": "Rondônia", "casos": 33, "morte": 2, "letalidade": 6.1},
  {"estado": "Roraima", "casos": 75, "morte": 3, "letalidade": 4.0},
  {"estado": "Santa Catarina", "casos": 693, "morte": 18, "letalidade": 2.6},
  {"estado": "Sergipe", "casos": 42, "morte": 4, "letalidade": 9.5},
  {"estado": "São Paulo", "casos": 8419, "morte": 560, "letalidade": 6.7},
  {"estado": "Tocantins", "casos": 23, "morte": 0, "letalidade": 0},
];
